// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx2Gh8yr-sAyLIimWQVQxj_PWSbi_xpt4',
    appId: '1:461937855627:web:a2a5e6c8fbf30a9e5a188e',
    messagingSenderId: '461937855627',
    projectId: 'movie-cfffe',
    authDomain: 'movie-cfffe.firebaseapp.com',
    storageBucket: 'movie-cfffe.appspot.com',
    measurementId: 'G-P26BQ5H54V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1BUpm2X6yUc4vv3s6ESi9cyVcbK7akBM',
    appId: '1:461937855627:android:4f570e7dd2e6a0035a188e',
    messagingSenderId: '461937855627',
    projectId: 'movie-cfffe',
    storageBucket: 'movie-cfffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDa63JhAsB--NCC9rf9_VJoVMX6GcNTg',
    appId: '1:461937855627:ios:df8f1372a01262715a188e',
    messagingSenderId: '461937855627',
    projectId: 'movie-cfffe',
    storageBucket: 'movie-cfffe.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGDa63JhAsB--NCC9rf9_VJoVMX6GcNTg',
    appId: '1:461937855627:ios:df8f1372a01262715a188e',
    messagingSenderId: '461937855627',
    projectId: 'movie-cfffe',
    storageBucket: 'movie-cfffe.appspot.com',
    iosBundleId: 'com.example.movie',
  );
}
